default: &default
  host: localhost
  adapter: postgresql
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: carona_ufal_development

test:
  <<: *default
  database: carona_ufal_test

